apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-spark-debug-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  run.sh: |
    #!/usr/bin/env bash
    set -e

    /spark-worker \
      --master-port={{ .Values.master.servicePort }} \
      --webui-port={{ .Values.master.webAdmin.servicePort }} \
      --master-hostname={{ template "spark.master-name" . }}
